app:
  version: 0.1
  base-url: http://d58e88f4.ngrok.io
  client-origin: http://localhost:3000
  spotify-credentials:
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
  tunefind-credentials:
    username: ${TUNEFIND_USERNAME}
    password: ${TUNEFIND_PASSWORD}
    api-endpoint: ${TUNEFIND_API_ENDPOINT}
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
    schema-location-pattern: "**/*.graphqls"
graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  cdn:
    enabled: true
  pageTitle: GraphiQL Explorer
