app:
  version: 0.1
  base-url: http://d58e88f4.ngrok.io
  client-origin: http://localhost:3000
  spotify-credentials:
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
  tunefind-credentials:
    username: ${TUNEFIND_USERNAME}
    password: ${TUNEFIND_PASSWORD}
    api-endpoint: ${TUNEFIND_API_ENDPOINT}
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
  tools:
    schema-location-pattern: "**/*.graphqls"
graphiql:
  enabled: true
  cdn:
    enabled: true
